on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n trondsAKSRegistry -g trondsAKSRegistry8fbb-rg --location "North Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n trondsAKSRegistry --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n trondsAKSRegistry --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n trondsAKSRegistry --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: trondsaksregistry.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t trondsaksregistry.azurecr.io/kuarcluster:${{ github.sha }}
        docker push trondsaksregistry.azurecr.io/kuarcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kuarcluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kuarcluster8acf | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kuarcluster8acf`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kuarcluster8acf
        container-registry-url: trondsaksregistry.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: kuarclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: kuarcluster8acf
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          trondsaksregistry.azurecr.io/kuarcluster:${{ github.sha }}
        imagepullsecrets: |
          kuarclusterdockerauth